export const TYPES = {
  GET_INFO_DOWNLOAD_REQUEST: "GET_INFO_DOWNLOAD_REQUEST",
  GET_INFO_DOWNLOAD_SUCCESS: "GET_INFO_DOWNLOAD_SUCCESS",
  GET_INFO_DOWNLOAD_FAIL: "GET_INFO_DOWNLOAD_FAIL",

  GET_INFO_DOWNLOAD_ID_REQUEST: "GET_INFO_DOWNLOAD_ID_REQUEST",
  GET_INFO_DOWNLOAD_ID_SUCCESS: "GET_INFO_DOWNLOAD_ID_SUCCESS",
  GET_INFO_DOWNLOAD_ID_FAIL: "GET_INFO_DOWNLOAD_ID_FAIL",

  DOWNLOAD_VIDEO_REQUEST: "DOWNLOAD_VIDEO_REQUEST",
  DOWNLOAD_VIDEO_SUCCESS: "DOWNLOAD_VIDEO_SUCCESS",
  DOWNLOAD_VIDEO_FAIL: "DOWNLOAD_VIDEO_FAIL",

  DOWNLOAD_AUDIO_REQUEST: "DOWNLOAD_AUDIO_REQUEST",
  DOWNLOAD_AUDIO_SUCCESS: "DOWNLOAD_AUDIO_SUCCESS",
  DOWNLOAD_AUDIO_FAIL: "DOWNLOAD_AUDIO_FAIL",
};
